"""add weather residualization fields to asset_baselines

Revision ID: 3317f58cec87
Revises: a50f8bea32d8
Create Date: 2026-07-29 19:30:07.797331

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3317f58cec87"
down_revision: str | Sequence[str] | None = "a50f8bea32d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset_baselines", sa.Column("weather_col", sa.String(), nullable=False))
    op.add_column("asset_baselines", sa.Column("weather_slope", sa.Float(), nullable=False))
    op.add_column("asset_baselines", sa.Column("weather_intercept", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_baselines", "weather_intercept")
    op.drop_column("asset_baselines", "weather_slope")
    op.drop_column("asset_baselines", "weather_col")
    # ### end Alembic commands ###
