"""create asset_baselines table

Revision ID: a50f8bea32d8
Revises:
Create Date: 2026-07-29 19:23:53.299036

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a50f8bea32d8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_baselines",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("metric_definition_id", sa.String(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=False),
        sa.Column("std", sa.Float(), nullable=False),
        sa.Column("n_reference_rows", sa.Integer(), nullable=False),
        sa.Column("fit_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_baselines_asset_id"), "asset_baselines", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_baselines_metric_definition_id"),
        "asset_baselines",
        ["metric_definition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_asset_baselines_metric_definition_id"), table_name="asset_baselines")
    op.drop_index(op.f("ix_asset_baselines_asset_id"), table_name="asset_baselines")
    op.drop_table("asset_baselines")
    # ### end Alembic commands ###
