"""add organization_id to asset_types

Revision ID: deb905b4c875
Revises:
Create Date: 2026-08-14 13:04:18.329245

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "deb905b4c875"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added nullable first, then backfilled, then made NOT NULL - the
    # autogenerated version added this column NOT NULL directly with no
    # default, which fails against the real, already-populated
    # asset_types table (6 existing rows). Postgres has nothing to put
    # in a NOT NULL column with no default for rows that already exist.
    op.add_column("asset_types", sa.Column("organization_id", sa.String(length=36), nullable=True))

    # Backfill: every asset type that existed before this migration was
    # created and used exclusively by "ML Test Org", the only real,
    # active organization in use up to this point (org_id per the
    # project's own established test-org provenance).
    op.execute(
        "UPDATE asset_types SET organization_id = '5bead572-4221-4bc3-8705-7783f8fd4efe' "
        "WHERE organization_id IS NULL"
    )

    op.alter_column("asset_types", "organization_id", nullable=False)
    op.drop_constraint(op.f("asset_types_name_key"), "asset_types", type_="unique")
    op.create_index(
        op.f("ix_asset_types_organization_id"), "asset_types", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_asset_type_org_name", "asset_types", ["organization_id", "name"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_asset_type_org_name", "asset_types", type_="unique")
    op.drop_index(op.f("ix_asset_types_organization_id"), table_name="asset_types")
    op.create_unique_constraint(
        op.f("asset_types_name_key"), "asset_types", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("asset_types", "organization_id")
    # ### end Alembic commands ###
