import { ForcedTheme } from "@/lib/theme/ThemeProvider";
import { ChatPanel } from "@/components/copilot/ChatPanel";

export default function CopilotPage() {
  return (
    <ForcedTheme theme="dark">
      <div className="flex h-[calc(100vh-8rem)] flex-col rounded-xl border border-border bg-bg text-text-primary">
        <div className="border-b border-border p-4">
          <h1 className="font-display text-lg font-semibold text-text-primary">AI Copilot</h1>
          <p className="text-sm text-text-muted">
            Preview only — answers are illustrative, not generated by a real model yet.
          </p>
        </div>
        <ChatPanel />
      </div>
    </ForcedTheme>
  );
}
